# Generated by Django 4.2.6 on 2024-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_people_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='year',
            field=models.IntegerField(),
        ),
    ]
