# Generated by Django 4.2.6 on 2024-04-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_entries_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.people'),
        ),
    ]
